### ISSUE TITLE
quiver tried to install other version of tensorflow

### ISSUE THREAD

**Issue by vladimircape** [keplr-io/quiver#61] opened 2017-12-07 12:40 UTC
I have tensorflow-gpu and keras,
but when i tried to install your application, your application start to install
```
keras:           2.0.8-py36hc0b6f7c_0                 
    quiver_engine:   0.1.4.1.4-py36_0      jjh_cio_testing
    tensorflow:      1.3.0-0               jjh_cio_testing
    tensorflow-base: 1.3.0-py36h5293eaa_1  jjh_cio_testing
```

i have
```
keras-gpu                 2.0.5                    py36_0    anaconda
tensorflow-gpu            1.3.0                         0    anaconda
tensorflow-gpu-base       1.3.0           py36cuda8.0cudnn6.0_0    anaconda
tensorflow-tensorboard    0.1.5                    py36_0    anaconda

```

**Comment by taichu012** [comment] 2017-12-17 12:32
same  as #59 which is I met.

**Comment by jakebian** [comment] 2018-05-15 20:16
Duplicate of https://github.com/keplr-io/quiver/issues/59

**Closed by jakebian** 2018-05-15 20:16 UTC
